# Generated by Django 5.2.7 on 2025-10-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_pago_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Comprobante enviado'), ('VALIDADO', 'Validado por admin'), ('RECHAZADO', 'Rechazado por admin')], default='PENDIENTE', max_length=12),
        ),
    ]
