# Generated by Django 5.2.7 on 2025-10-28 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_dias', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ALUMNO', 'Alumno'), ('PROFESOR', 'Profesor'), ('ADMIN', 'Administrador')], max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('documento', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='Completado', max_length=20)),
                ('membresia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.membresia')),
                ('alumno', models.ForeignKey(blank=True, limit_choices_to={'rol': 'ALUMNO'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_core', to='core.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.FileField(upload_to='documentos/cedulas/')),
                ('estado_cedula', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('eps', models.FileField(upload_to='documentos/eps/')),
                ('estado_eps', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('autorizacion', models.FileField(upload_to='documentos/autorizaciones/')),
                ('estado_autorizacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(limit_choices_to={'rol': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_core', to='core.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('presente', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(blank=True, limit_choices_to={'rol': 'ALUMNO'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_recibidas', to='core.perfil')),
                ('profesor', models.ForeignKey(limit_choices_to={'rol': 'PROFESOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_registradas', to='core.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(blank=True, limit_choices_to={'rol': 'ALUMNO'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progresos_core', to='core.perfil')),
                ('nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nivel')),
            ],
        ),
    ]
