# Generated by Django 5.2.7 on 2025-10-28 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('alumnos', models.ManyToManyField(blank=True, limit_choices_to={'rol': 'ALUMNO'}, related_name='grupos_alumno', to='core.perfil')),
                ('profesor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'PROFESOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_dirigidos', to='core.perfil')),
            ],
        ),
    ]
